default_stages: [ pre-push ]
fail_fast: false
exclude: '(^external/|^docs/|^tmp/)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-docstring-first
      - id: debug-statements
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]

  - repo: local
    hooks:
      - id: format
        name: Format Code with Ruff
        entry: make format
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: lint
        name: Lint Code with Ruff
        entry: make lint
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: typecheck
        name: Type Check with Pyright
        entry: make typecheck
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: test
        name: Run Tests
        entry: make test
        language: system
        pass_filenames: false
        stages: [ pre-push ]
